import Foundation

// MARK: - Browsers table
// Ported from tw93/Mole lib/clean/user.sh (GPL-3.0), `clean_browsers` and the
// old-version pruners (`clean_chrome_old_versions`, `clean_edge_old_versions`,
// `clean_edge_updater_old_versions`, `clean_brave_old_versions`).
// Scope: Safari, Chrome/Chromium, Edge, Brave, Firefox. Data only — no disk access.

/// Chrome runs under helper process names too, so its probe is wider than
/// pgrep -x (mole lib/clean/user.sh:610-615).
private let chromeGuard = MoleProcessGuard(
    family: "Chrome",
    exactProcessNames: ["Google Chrome", "Google Chrome Helper"],
    pathSubstrings: ["/Google Chrome.app/"]
)
private let edgeGuard = MoleProcessGuard.exact("Microsoft Edge")
private let braveGuard = MoleProcessGuard.exact("Brave Browser")
private let firefoxGuard = MoleProcessGuard.exact("Firefox")
private let arcGuard = MoleProcessGuard.exact("Arc")
private let diaGuard = MoleProcessGuard.exact("Dia")
private let vivaldiGuard = MoleProcessGuard.exact("Vivaldi")
private let qqBrowserGuard = MoleProcessGuard.exact("QQBrowser3")

public enum Browsers {

    // Builds a row for this table: home-relative, safe by default.
    private static func target(
        _ label: String,
        _ path: String,
        kind: MoleTargetKind,
        explanation: String,
        processGuard: MoleProcessGuard? = nil,
        pruneRule: MolePruneRule? = nil,
        source: String
    ) -> CleanTarget {
        CleanTarget(
            label: label,
            group: .browsers,
            path: .homeRelative(path),
            kind: kind,
            explanation: explanation,
            processGuard: processGuard,
            pruneRule: pruneRule,
            source: source
        )
    }

    // Absolute app-bundle rows (old-version pruning) need the full initializer.
    private static func appBundle(
        _ label: String,
        path: MolePath,
        framework: String,
        explanation: String,
        source: String,
        processGuard: MoleProcessGuard
    ) -> CleanTarget {
        CleanTarget(
            label: label,
            group: .browsers,
            path: path,
            kind: .frameworkVersions(framework: framework),
            explanation: explanation,
            processGuard: processGuard,
            pruneRule: .keepCurrentSymlinkTarget,
            source: source
        )
    }

    private static let chromeSupport = "Library/Application Support/Google/Chrome"
    private static let braveSupport = "Library/Application Support/BraveSoftware/Brave-Browser"

    public static let all: [CleanTarget] = [
        // -- Safari -----------------------------------------------------------------
        target(
            "Safari cache",
            "Library/Caches/com.apple.Safari",
            kind: .directorySweep,
            explanation: "Safari HTTP/cache files. Re-downloaded as you browse; history, bookmarks and passwords live elsewhere and are untouched.",
            source: "mole lib/clean/user.sh:1695"
        ),

        // -- Chrome -----------------------------------------------------------------
        target(
            "Chrome cache",
            "Library/Caches/Google/Chrome",
            kind: .directorySweep,
            explanation: "Chrome's HTTP cache root. Rebuilt as you browse; profile data is untouched.",
            source: "mole lib/clean/user.sh:1697"
        ),
        target(
            "Chrome app cache",
            "\(chromeSupport)/*/Application Cache/*",
            kind: .glob,
            explanation: "Per-profile legacy app cache. Regenerated by the pages that use it.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:643"
        ),
        target(
            "Chrome code cache",
            "\(chromeSupport)/*/Code Cache/*",
            kind: .glob,
            explanation: "Compiled JavaScript bytecode per profile. Recompiled on next page load.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:645"
        ),
        target(
            "Chrome GPU cache",
            "\(chromeSupport)/*/GPUCache/*",
            kind: .glob,
            explanation: "GPU shader/command scratch per profile. Rebuilt by the GPU process.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:647"
        ),
        target(
            "Chrome Dawn cache",
            "\(chromeSupport)/*/DawnCache/*",
            kind: .glob,
            explanation: "WebGPU/Dawn pipeline cache per profile. Regenerated on next WebGPU use.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:649"
        ),
        target(
            "Chrome GR shader cache",
            "\(chromeSupport)/*/GrShaderCache/*",
            kind: .glob,
            explanation: "Skia shader cache per profile. Recompiled as pages render.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:651"
        ),
        target(
            "Chrome Graphite Dawn cache",
            "\(chromeSupport)/*/GraphiteDawnCache/*",
            kind: .glob,
            explanation: "Graphite-backed WebGPU cache per profile. Regenerated on demand.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:653"
        ),
        target(
            "Chrome component CRX cache",
            "\(chromeSupport)/component_crx_cache",
            kind: .directorySweep,
            explanation: "Component-updater extension payloads. Re-downloaded by the updater.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:655"
        ),
        target(
            "Chrome shader cache",
            "\(chromeSupport)/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache. Recompiled as pages render.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:657"
        ),
        target(
            "Chrome GR shader cache",
            "\(chromeSupport)/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache. Recompiled as pages render.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:659"
        ),
        target(
            "Chrome Dawn cache",
            "\(chromeSupport)/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite/WebGPU cache. Regenerated on demand.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:661"
        ),
        target(
            "Chrome crash reports",
            "\(chromeSupport)/Crashpad/completed",
            kind: .directorySweep,
            explanation: "Minidumps already offered for upload. Purely diagnostic.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:663"
        ),
        target(
            "Chrome on-device model cache",
            "\(chromeSupport)/OptGuideOnDeviceModel",
            kind: .directorySweep,
            explanation: "On-device AI model downloads, often multiple GB. Re-downloaded on demand by Chrome's component updater.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:665"
        ),
        target(
            "Chrome on-device classifier cache",
            "\(chromeSupport)/OptGuideOnDeviceClassifierModel",
            kind: .directorySweep,
            explanation: "On-device classifier model payloads. Re-downloaded on demand.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:667"
        ),
        target(
            "Chrome optimization guide models",
            "\(chromeSupport)/optimization_guide_model_store",
            kind: .directorySweep,
            explanation: "Optimization-guide model store. Re-downloaded on demand.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:669"
        ),
        target(
            "Chrome service worker cache",
            "\(chromeSupport)/*/Service Worker/CacheStorage",
            kind: .glob,
            explanation: "Per-origin service-worker CacheStorage. Never touches ScriptCache (MV3 extension bytecode) and honors the protected-domain list.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:1734"
        ),
        target(
            "GoogleUpdater CRX cache",
            "Library/Application Support/Google/GoogleUpdater/crx_cache",
            kind: .directorySweep,
            explanation: "GoogleUpdater component payload cache. Re-fetched by the updater.",
            source: "mole lib/clean/user.sh:1737"
        ),
        target(
            "GoogleUpdater old files",
            "Library/Application Support/Google/GoogleUpdater/*.old",
            kind: .glob,
            explanation: "Superseded updater artifacts renamed .old during updates.",
            source: "mole lib/clean/user.sh:1738"
        ),
        target(
            "Chromium cache",
            "Library/Caches/Chromium",
            kind: .directorySweep,
            explanation: "Chromium open-source build's cache root. Same layout as Chrome's.",
            source: "mole lib/clean/user.sh:1739"
        ),
        appBundle(
            "Chrome old versions (system app)",
            path: .absolute("/Applications/Google Chrome.app"),
            framework: "Google Chrome Framework.framework",
            explanation: "Old Chrome framework versions under Contents/Frameworks/.../Versions. Keeps the Current symlink target and any newer staged auto-update; may need elevated permissions to remove.",
            source: "mole lib/clean/user.sh:688",
            processGuard: chromeGuard
        ),
        appBundle(
            "Chrome old versions (user app)",
            path: .homeRelative("Applications/Google Chrome.app"),
            framework: "Google Chrome Framework.framework",
            explanation: "Same pruning for a per-user Chrome install. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:693",
            processGuard: chromeGuard
        ),

        // -- Edge ------------------------------------------------------------------
        target(
            "Edge cache",
            "Library/Caches/com.microsoft.edgemac",
            kind: .directorySweep,
            explanation: "Microsoft Edge HTTP cache. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1741"
        ),
        appBundle(
            "Edge old versions (system app)",
            path: .absolute("/Applications/Microsoft Edge.app"),
            framework: "Microsoft Edge Framework.framework",
            explanation: "Old Edge framework versions. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:704",
            processGuard: edgeGuard
        ),
        appBundle(
            "Edge old versions (user app)",
            path: .homeRelative("Applications/Microsoft Edge.app"),
            framework: "Microsoft Edge Framework.framework",
            explanation: "Same pruning for a per-user Edge install. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:709",
            processGuard: edgeGuard
        ),
        target(
            "Edge updater old versions",
            "Library/Application Support/Microsoft/EdgeUpdater/apps/msedge-stable",
            kind: .directorySweep,
            explanation: "EdgeUpdater staged payloads. There is no Current symlink here: keeps anything not strictly older than the installed Edge version.",
            processGuard: edgeGuard,
            pruneRule: .keepInstalledOrNewerVersion,
            source: "mole lib/clean/user.sh:720"
        ),

        // -- Brave -----------------------------------------------------------------
        target(
            "Brave cache",
            "Library/Caches/BraveSoftware/Brave-Browser",
            kind: .directorySweep,
            explanation: "Brave's HTTP cache root. Rebuilt as you browse; profile data is untouched.",
            source: "mole lib/clean/user.sh:1816"
        ),
        target(
            "Brave app cache",
            "\(braveSupport)/*/Application Cache/*",
            kind: .glob,
            explanation: "Per-profile legacy app cache. Regenerated by the pages that use it.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1821"
        ),
        target(
            "Brave code cache",
            "\(braveSupport)/*/Code Cache/*",
            kind: .glob,
            explanation: "Compiled JavaScript bytecode per profile. Recompiled on next page load.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1822"
        ),
        target(
            "Brave GPU cache",
            "\(braveSupport)/*/GPUCache/*",
            kind: .glob,
            explanation: "GPU shader/command scratch per profile. Rebuilt by the GPU process.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1823"
        ),
        target(
            "Brave Dawn cache",
            "\(braveSupport)/*/DawnCache/*",
            kind: .glob,
            explanation: "WebGPU/Dawn pipeline cache per profile. Regenerated on next WebGPU use.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1824"
        ),
        target(
            "Brave GR shader cache",
            "\(braveSupport)/*/GrShaderCache/*",
            kind: .glob,
            explanation: "Skia shader cache per profile. Recompiled as pages render.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1825"
        ),
        target(
            "Brave Graphite Dawn cache",
            "\(braveSupport)/*/GraphiteDawnCache/*",
            kind: .glob,
            explanation: "Graphite-backed WebGPU cache per profile. Regenerated on demand.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1826"
        ),
        target(
            "Brave component CRX cache",
            "\(braveSupport)/component_crx_cache",
            kind: .directorySweep,
            explanation: "Component-updater extension payloads. Re-downloaded by the updater.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1827"
        ),
        target(
            "Brave shader cache",
            "\(braveSupport)/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache. Recompiled as pages render.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1828"
        ),
        target(
            "Brave GR shader cache",
            "\(braveSupport)/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache. Recompiled as pages render.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1829"
        ),
        target(
            "Brave Dawn cache",
            "\(braveSupport)/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite/WebGPU cache. Regenerated on demand.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1830"
        ),
        target(
            "Brave crash reports",
            "\(braveSupport)/Crashpad/completed",
            kind: .directorySweep,
            explanation: "Minidumps already offered for upload. Purely diagnostic.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1831"
        ),
        target(
            "Brave service worker cache",
            "\(braveSupport)/*/Service Worker/CacheStorage",
            kind: .glob,
            explanation: "Per-origin service-worker CacheStorage. ScriptCache (MV3 bytecode) and protected domains are never touched.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1833"
        ),
        appBundle(
            "Brave old versions (system app)",
            path: .absolute("/Applications/Brave Browser.app"),
            framework: "Brave Browser Framework.framework",
            explanation: "Old Brave framework versions. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:853",
            processGuard: braveGuard
        ),
        appBundle(
            "Brave old versions (user app)",
            path: .homeRelative("Applications/Brave Browser.app"),
            framework: "Brave Browser Framework.framework",
            explanation: "Same pruning for a per-user Brave install. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:858",
            processGuard: braveGuard
        ),

        // -- Firefox ----------------------------------------------------------------
        target(
            "Firefox cache",
            "Library/Caches/Firefox",
            kind: .directorySweep,
            explanation: "Firefox HTTP cache root. Rebuilt as you browse.",
            processGuard: firefoxGuard,
            source: "mole lib/clean/user.sh:674"
        ),
        target(
            "Firefox profile cache",
            "Library/Application Support/Firefox/Profiles/*/cache2/*",
            kind: .glob,
            explanation: "Per-profile cache2 contents. Regenerated on next use; bookmarks, history and logins are untouched.",
            processGuard: firefoxGuard,
            source: "mole lib/clean/user.sh:676"
        ),

        // -- Puppeteer -----------------------------------------------------------------
        target(
            "Puppeteer browser cache",
            ".cache/puppeteer",
            kind: .directorySweep,
            explanation: "Puppeteer's downloaded Chromium builds. Re-downloaded on demand by Puppeteer.",
            source: "mole lib/clean/user.sh:1740"
        ),

        // -- Arc ----------------------------------------------------------------------
        target(
            "Arc cache",
            "Library/Caches/company.thebrowser.Browser",
            kind: .directorySweep,
            explanation: "Arc's HTTP cache root. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1744"
        ),
        target(
            "Arc code cache",
            "Library/Application Support/Arc/*/Code Cache/*",
            kind: .glob,
            explanation: "Per-profile compiled JavaScript bytecode. Recompiled on next page load.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1749"
        ),
        target(
            "Arc GPU cache",
            "Library/Application Support/Arc/*/GPUCache/*",
            kind: .glob,
            explanation: "Per-profile GPU scratch. Rebuilt by the GPU process.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1750"
        ),
        target(
            "Arc Dawn cache",
            "Library/Application Support/Arc/*/DawnCache/*",
            kind: .glob,
            explanation: "Per-profile WebGPU/Dawn cache. Regenerated on next WebGPU use.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1751"
        ),
        target(
            "Arc GR shader cache",
            "Library/Application Support/Arc/*/GrShaderCache/*",
            kind: .glob,
            explanation: "Per-profile Skia shader cache. Recompiled as pages render.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1752"
        ),
        target(
            "Arc Graphite Dawn cache",
            "Library/Application Support/Arc/*/GraphiteDawnCache/*",
            kind: .glob,
            explanation: "Per-profile Graphite-backed WebGPU cache. Regenerated on demand.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1753"
        ),
        target(
            "Arc shader cache",
            "Library/Application Support/Arc/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache. Recompiled as pages render.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1754"
        ),
        target(
            "Arc GR shader cache",
            "Library/Application Support/Arc/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache. Recompiled as pages render.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1755"
        ),
        target(
            "Arc Dawn cache",
            "Library/Application Support/Arc/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite/WebGPU cache. Regenerated on demand.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1756"
        ),
        target(
            "Arc crash reports",
            "Library/Application Support/Arc/Crashpad/completed",
            kind: .directorySweep,
            explanation: "Minidumps already offered for upload. Purely diagnostic.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1757"
        ),
        target(
            "Arc code cache (User Data)",
            "Library/Application Support/Arc/User Data/*/Code Cache/*",
            kind: .glob,
            explanation: "Same code-cache layout under Arc's User Data root. Recompiled on next page load.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1758"
        ),
        target(
            "Arc GPU cache (User Data)",
            "Library/Application Support/Arc/User Data/*/GPUCache/*",
            kind: .glob,
            explanation: "GPU scratch under Arc's User Data root. Rebuilt by the GPU process.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1759"
        ),
        target(
            "Arc Dawn cache (User Data)",
            "Library/Application Support/Arc/User Data/*/DawnCache/*",
            kind: .glob,
            explanation: "WebGPU/Dawn cache under Arc's User Data root. Regenerated on demand.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1760"
        ),
        target(
            "Arc GR shader cache (User Data)",
            "Library/Application Support/Arc/User Data/*/GrShaderCache/*",
            kind: .glob,
            explanation: "Skia shader cache under Arc's User Data root. Recompiled as pages render.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1761"
        ),
        target(
            "Arc Graphite Dawn cache (User Data)",
            "Library/Application Support/Arc/User Data/*/GraphiteDawnCache/*",
            kind: .glob,
            explanation: "Graphite/WebGPU cache under Arc's User Data root. Regenerated on demand.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1762"
        ),
        target(
            "Arc shader cache (User Data)",
            "Library/Application Support/Arc/User Data/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache under User Data. Recompiled as pages render.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1763"
        ),
        target(
            "Arc GR shader cache (User Data)",
            "Library/Application Support/Arc/User Data/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache under User Data. Recompiled as pages render.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1764"
        ),
        target(
            "Arc Dawn cache (User Data)",
            "Library/Application Support/Arc/User Data/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite cache under User Data. Regenerated on demand.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1765"
        ),
        target(
            "Arc component CRX cache",
            "Library/Application Support/Arc/User Data/component_crx_cache",
            kind: .directorySweep,
            explanation: "Component-updater extension payloads. Re-downloaded by the updater.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1766"
        ),
        target(
            "Arc extensions CRX cache",
            "Library/Application Support/Arc/User Data/extensions_crx_cache",
            kind: .directorySweep,
            explanation: "Extension CRX payload cache. Re-fetched by the extension updater.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1767"
        ),
        target(
            "Arc crash reports (User Data)",
            "Library/Application Support/Arc/User Data/Crashpad/completed",
            kind: .directorySweep,
            explanation: "Minidumps already offered for upload. Purely diagnostic.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1768"
        ),
        target(
            "Arc service worker cache",
            "Library/Application Support/Arc/*/Service Worker/CacheStorage",
            kind: .glob,
            explanation: "Per-origin service-worker CacheStorage; MV3 ScriptCache is never touched.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1771"
        ),
        target(
            "Arc service worker cache (User Data)",
            "Library/Application Support/Arc/User Data/*/Service Worker/CacheStorage",
            kind: .glob,
            explanation: "Service-worker CacheStorage under Arc's User Data root; ScriptCache is never touched.",
            processGuard: arcGuard,
            source: "mole lib/clean/user.sh:1775"
        ),

        // -- Dia ------------------------------------------------------------------------
        target(
            "Dia cache",
            "Library/Caches/company.thebrowser.dia",
            kind: .directorySweep,
            explanation: "Dia's bundle-ID cache root. Sparkle update state is protected upstream; the rest is rebuildable.",
            source: "mole lib/clean/user.sh:1783"
        ),
        target(
            "Dia HTTP cache",
            "Library/Caches/Dia/User Data/*/Cache/*",
            kind: .glob,
            explanation: "Per-profile HTTP cache. Rebuilt as you browse.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1795"
        ),
        target(
            "Dia code cache",
            "Library/Caches/Dia/User Data/*/Code Cache/*",
            kind: .glob,
            explanation: "Per-profile compiled bytecode. Recompiled on next page load.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1796"
        ),
        target(
            "Dia Graphite Dawn cache",
            "Library/Application Support/Dia/User Data/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Graphite/WebGPU cache. Regenerated on demand.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1797"
        ),
        target(
            "Dia GPU cache",
            "Library/Application Support/Dia/User Data/GPUPersistentCache",
            kind: .directorySweep,
            explanation: "Persistent GPU cache. Rebuilt by the GPU process.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1798"
        ),
        target(
            "Dia component CRX cache",
            "Library/Application Support/Dia/User Data/component_crx_cache",
            kind: .directorySweep,
            explanation: "Component-updater payloads. Re-downloaded by the updater.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1799"
        ),
        target(
            "Dia extensions CRX cache",
            "Library/Application Support/Dia/User Data/extensions_crx_cache",
            kind: .directorySweep,
            explanation: "Extension CRX payload cache. Re-fetched on demand.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1800"
        ),
        target(
            "Dia Dawn Graphite cache",
            "Library/Application Support/Dia/User Data/*/DawnGraphiteCache/*",
            kind: .glob,
            explanation: "Per-profile Dawn Graphite cache. Regenerated on demand.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1801"
        ),
        target(
            "Dia Dawn WebGPU cache",
            "Library/Application Support/Dia/User Data/*/DawnWebGPUCache/*",
            kind: .glob,
            explanation: "Per-profile Dawn WebGPU cache. Regenerated on demand.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1802"
        ),
        target(
            "Dia GPU cache (per profile)",
            "Library/Application Support/Dia/User Data/*/GPUCache/*",
            kind: .glob,
            explanation: "Per-profile GPU scratch. Rebuilt by the GPU process.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1803"
        ),
        target(
            "Dia service worker cache",
            "Library/Application Support/Dia/User Data/*/Service Worker/CacheStorage",
            kind: .glob,
            explanation: "Per-origin service-worker CacheStorage; MV3 ScriptCache is never touched.",
            processGuard: diaGuard,
            source: "mole lib/clean/user.sh:1812"
        ),

        // -- Helium ----------------------------------------------------------------------
        target(
            "Helium cache",
            "Library/Caches/net.imput.helium",
            kind: .directorySweep,
            explanation: "Helium's cache root. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1839"
        ),
        target(
            "Helium GPU cache",
            "Library/Application Support/net.imput.helium/*/GPUCache/*",
            kind: .glob,
            explanation: "Per-profile GPU scratch. Rebuilt by the GPU process.",
            source: "mole lib/clean/user.sh:1840"
        ),
        target(
            "Helium component cache",
            "Library/Application Support/net.imput.helium/component_crx_cache",
            kind: .directorySweep,
            explanation: "Component-updater payloads. Re-downloaded by the updater.",
            source: "mole lib/clean/user.sh:1841"
        ),
        target(
            "Helium extensions cache",
            "Library/Application Support/net.imput.helium/extensions_crx_cache",
            kind: .directorySweep,
            explanation: "Extension CRX payload cache. Re-fetched on demand.",
            source: "mole lib/clean/user.sh:1842"
        ),
        target(
            "Helium shader cache",
            "Library/Application Support/net.imput.helium/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache. Recompiled as pages render.",
            source: "mole lib/clean/user.sh:1843"
        ),
        target(
            "Helium Dawn cache",
            "Library/Application Support/net.imput.helium/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite/WebGPU cache. Regenerated on demand.",
            source: "mole lib/clean/user.sh:1844"
        ),
        target(
            "Helium shader cache (ShaderCache)",
            "Library/Application Support/net.imput.helium/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache. Recompiled as pages render.",
            source: "mole lib/clean/user.sh:1845"
        ),
        target(
            "Helium app cache",
            "Library/Application Support/net.imput.helium/*/Application Cache/*",
            kind: .glob,
            explanation: "Per-profile legacy app cache. Regenerated by the pages that use it.",
            source: "mole lib/clean/user.sh:1846"
        ),

        // -- Yandex -----------------------------------------------------------------------
        target(
            "Yandex cache",
            "Library/Caches/Yandex/YandexBrowser",
            kind: .directorySweep,
            explanation: "Yandex Browser's HTTP cache root. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1850"
        ),
        target(
            "Yandex shader cache",
            "Library/Application Support/Yandex/YandexBrowser/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache. Recompiled as pages render.",
            source: "mole lib/clean/user.sh:1851"
        ),
        target(
            "Yandex GR shader cache",
            "Library/Application Support/Yandex/YandexBrowser/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache. Recompiled as pages render.",
            source: "mole lib/clean/user.sh:1852"
        ),
        target(
            "Yandex Dawn cache",
            "Library/Application Support/Yandex/YandexBrowser/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite/WebGPU cache. Regenerated on demand.",
            source: "mole lib/clean/user.sh:1853"
        ),
        target(
            "Yandex GPU cache",
            "Library/Application Support/Yandex/YandexBrowser/*/GPUCache/*",
            kind: .glob,
            explanation: "Per-profile GPU scratch. Rebuilt by the GPU process.",
            source: "mole lib/clean/user.sh:1854"
        ),

        // -- Opera --------------------------------------------------------------------------
        target(
            "Opera cache",
            "Library/Caches/com.operasoftware.Opera",
            kind: .directorySweep,
            explanation: "Opera's cache root. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1872"
        ),

        // -- Vivaldi ------------------------------------------------------------------------
        target(
            "Vivaldi cache",
            "Library/Caches/com.vivaldi.Vivaldi",
            kind: .directorySweep,
            explanation: "Vivaldi's HTTP cache root. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1875"
        ),
        target(
            "Vivaldi code cache",
            "Library/Application Support/Vivaldi/*/Code Cache/*",
            kind: .glob,
            explanation: "Per-profile compiled bytecode. Recompiled on next page load.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1880"
        ),
        target(
            "Vivaldi GPU cache",
            "Library/Application Support/Vivaldi/*/GPUCache/*",
            kind: .glob,
            explanation: "Per-profile GPU scratch. Rebuilt by the GPU process.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1881"
        ),
        target(
            "Vivaldi Dawn cache",
            "Library/Application Support/Vivaldi/*/DawnCache/*",
            kind: .glob,
            explanation: "Per-profile WebGPU/Dawn cache. Regenerated on demand.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1882"
        ),
        target(
            "Vivaldi GR shader cache",
            "Library/Application Support/Vivaldi/*/GrShaderCache/*",
            kind: .glob,
            explanation: "Per-profile Skia shader cache. Recompiled as pages render.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1883"
        ),
        target(
            "Vivaldi Graphite Dawn cache",
            "Library/Application Support/Vivaldi/*/GraphiteDawnCache/*",
            kind: .glob,
            explanation: "Per-profile Graphite-backed WebGPU cache. Regenerated on demand.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1884"
        ),
        target(
            "Vivaldi shader cache",
            "Library/Application Support/Vivaldi/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache. Recompiled as pages render.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1885"
        ),
        target(
            "Vivaldi GR shader cache",
            "Library/Application Support/Vivaldi/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache. Recompiled as pages render.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1886"
        ),
        target(
            "Vivaldi Dawn cache",
            "Library/Application Support/Vivaldi/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite/WebGPU cache. Regenerated on demand.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1887"
        ),
        target(
            "Vivaldi crash reports",
            "Library/Application Support/Vivaldi/Crashpad/completed",
            kind: .directorySweep,
            explanation: "Minidumps already offered for upload. Purely diagnostic.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1888"
        ),
        target(
            "Vivaldi service worker cache",
            "Library/Application Support/Vivaldi/*/Service Worker/CacheStorage",
            kind: .glob,
            explanation: "Per-origin service-worker CacheStorage; MV3 ScriptCache is never touched.",
            processGuard: vivaldiGuard,
            source: "mole lib/clean/user.sh:1891"
        ),

        // -- Comet / Orion / Zen ---------------------------------------------------------------
        target(
            "Comet cache",
            "Library/Caches/Comet",
            kind: .directorySweep,
            explanation: "Comet browser's cache root. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1894"
        ),
        target(
            "Orion cache",
            "Library/Caches/com.kagi.kagimacOS",
            kind: .directorySweep,
            explanation: "Orion (Kagi) browser's cache root. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1895"
        ),
        target(
            "Zen cache",
            "Library/Caches/zen",
            kind: .directorySweep,
            explanation: "Zen browser's cache root. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1896"
        ),

        // -- QQ Browser ------------------------------------------------------------------------
        target(
            "QQ Browser cache",
            "Library/Caches/com.tencent.QQBrowser3",
            kind: .directorySweep,
            explanation: "QQ Browser 3 (Chromium) cache root. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1903"
        ),
        target(
            "QQ Browser code cache",
            "Library/Application Support/QQBrowser3/*/Code Cache/*",
            kind: .glob,
            explanation: "Per-profile compiled bytecode. Recompiled on next page load.",
            processGuard: qqBrowserGuard,
            source: "mole lib/clean/user.sh:1907"
        ),
        target(
            "QQ Browser GPU cache",
            "Library/Application Support/QQBrowser3/*/GPUCache/*",
            kind: .glob,
            explanation: "Per-profile GPU scratch. Rebuilt by the GPU process.",
            processGuard: qqBrowserGuard,
            source: "mole lib/clean/user.sh:1908"
        ),
        target(
            "QQ Browser shader cache",
            "Library/Application Support/QQBrowser3/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache. Recompiled as pages render.",
            processGuard: qqBrowserGuard,
            source: "mole lib/clean/user.sh:1909"
        ),
        target(
            "QQ Browser GR shader cache",
            "Library/Application Support/QQBrowser3/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache. Recompiled as pages render.",
            processGuard: qqBrowserGuard,
            source: "mole lib/clean/user.sh:1910"
        ),
        target(
            "QQ Browser Dawn cache",
            "Library/Application Support/QQBrowser3/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite/WebGPU cache. Regenerated on demand.",
            processGuard: qqBrowserGuard,
            source: "mole lib/clean/user.sh:1911"
        ),
        target(
            "QQ Browser component cache",
            "Library/Application Support/QQBrowser3/component_crx_cache",
            kind: .directorySweep,
            explanation: "Component-updater payloads. Re-downloaded by the updater.",
            processGuard: qqBrowserGuard,
            source: "mole lib/clean/user.sh:1912"
        ),
        target(
            "QQ Browser crash reports",
            "Library/Application Support/QQBrowser3/Crashpad/completed",
            kind: .directorySweep,
            explanation: "Minidumps already offered for upload. Purely diagnostic.",
            processGuard: qqBrowserGuard,
            source: "mole lib/clean/user.sh:1913"
        ),
    ]
}
