import Foundation

// MARK: - Browsers table
// Ported from tw93/Mole lib/clean/user.sh (GPL-3.0), `clean_browsers` and the
// old-version pruners (`clean_chrome_old_versions`, `clean_edge_old_versions`,
// `clean_edge_updater_old_versions`, `clean_brave_old_versions`).
// Scope: Safari, Chrome/Chromium, Edge, Brave, Firefox. Data only — no disk access.

/// Chrome runs under helper process names too, so its probe is wider than
/// pgrep -x (mole lib/clean/user.sh:610-615).
private let chromeGuard = MoleProcessGuard(
    family: "Chrome",
    exactProcessNames: ["Google Chrome", "Google Chrome Helper"],
    pathSubstrings: ["/Google Chrome.app/"]
)
private let edgeGuard = MoleProcessGuard.exact("Microsoft Edge")
private let braveGuard = MoleProcessGuard.exact("Brave Browser")
private let firefoxGuard = MoleProcessGuard.exact("Firefox")

public enum Browsers {

    // Builds a row for this table: home-relative, safe by default.
    private static func target(
        _ label: String,
        _ path: String,
        kind: MoleTargetKind,
        explanation: String,
        processGuard: MoleProcessGuard? = nil,
        pruneRule: MolePruneRule? = nil,
        source: String
    ) -> CleanTarget {
        CleanTarget(
            label: label,
            group: .browsers,
            path: .homeRelative(path),
            kind: kind,
            explanation: explanation,
            processGuard: processGuard,
            pruneRule: pruneRule,
            source: source
        )
    }

    // Absolute app-bundle rows (old-version pruning) need the full initializer.
    private static func appBundle(
        _ label: String,
        _ appPath: String,
        framework: String,
        explanation: String,
        source: String,
        processGuard: MoleProcessGuard
    ) -> CleanTarget {
        CleanTarget(
            label: label,
            group: .browsers,
            path: .absolute(appPath),
            kind: .frameworkVersions(framework: framework),
            explanation: explanation,
            processGuard: processGuard,
            pruneRule: .keepCurrentSymlinkTarget,
            source: source
        )
    }

    private static let chromeSupport = "Library/Application Support/Google/Chrome"
    private static let braveSupport = "Library/Application Support/BraveSoftware/Brave-Browser"

    public static let all: [CleanTarget] = [
        // -- Safari -----------------------------------------------------------------
        target(
            "Safari cache",
            "Library/Caches/com.apple.Safari",
            kind: .directorySweep,
            explanation: "Safari HTTP/cache files. Re-downloaded as you browse; history, bookmarks and passwords live elsewhere and are untouched.",
            source: "mole lib/clean/user.sh:1695"
        ),

        // -- Chrome -----------------------------------------------------------------
        target(
            "Chrome cache",
            "Library/Caches/Google/Chrome",
            kind: .directorySweep,
            explanation: "Chrome's HTTP cache root. Rebuilt as you browse; profile data is untouched.",
            source: "mole lib/clean/user.sh:1697"
        ),
        target(
            "Chrome app cache",
            "\(chromeSupport)/*/Application Cache/*",
            kind: .glob,
            explanation: "Per-profile legacy app cache. Regenerated by the pages that use it.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:643"
        ),
        target(
            "Chrome code cache",
            "\(chromeSupport)/*/Code Cache/*",
            kind: .glob,
            explanation: "Compiled JavaScript bytecode per profile. Recompiled on next page load.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:645"
        ),
        target(
            "Chrome GPU cache",
            "\(chromeSupport)/*/GPUCache/*",
            kind: .glob,
            explanation: "GPU shader/command scratch per profile. Rebuilt by the GPU process.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:647"
        ),
        target(
            "Chrome Dawn cache",
            "\(chromeSupport)/*/DawnCache/*",
            kind: .glob,
            explanation: "WebGPU/Dawn pipeline cache per profile. Regenerated on next WebGPU use.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:649"
        ),
        target(
            "Chrome GR shader cache",
            "\(chromeSupport)/*/GrShaderCache/*",
            kind: .glob,
            explanation: "Skia shader cache per profile. Recompiled as pages render.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:651"
        ),
        target(
            "Chrome Graphite Dawn cache",
            "\(chromeSupport)/*/GraphiteDawnCache/*",
            kind: .glob,
            explanation: "Graphite-backed WebGPU cache per profile. Regenerated on demand.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:653"
        ),
        target(
            "Chrome component CRX cache",
            "\(chromeSupport)/component_crx_cache",
            kind: .directorySweep,
            explanation: "Component-updater extension payloads. Re-downloaded by the updater.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:655"
        ),
        target(
            "Chrome shader cache",
            "\(chromeSupport)/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache. Recompiled as pages render.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:657"
        ),
        target(
            "Chrome GR shader cache",
            "\(chromeSupport)/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache. Recompiled as pages render.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:659"
        ),
        target(
            "Chrome Dawn cache",
            "\(chromeSupport)/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite/WebGPU cache. Regenerated on demand.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:661"
        ),
        target(
            "Chrome crash reports",
            "\(chromeSupport)/Crashpad/completed",
            kind: .directorySweep,
            explanation: "Minidumps already offered for upload. Purely diagnostic.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:663"
        ),
        target(
            "Chrome on-device model cache",
            "\(chromeSupport)/OptGuideOnDeviceModel",
            kind: .directorySweep,
            explanation: "On-device AI model downloads, often multiple GB. Re-downloaded on demand by Chrome's component updater.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:665"
        ),
        target(
            "Chrome on-device classifier cache",
            "\(chromeSupport)/OptGuideOnDeviceClassifierModel",
            kind: .directorySweep,
            explanation: "On-device classifier model payloads. Re-downloaded on demand.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:667"
        ),
        target(
            "Chrome optimization guide models",
            "\(chromeSupport)/optimization_guide_model_store",
            kind: .directorySweep,
            explanation: "Optimization-guide model store. Re-downloaded on demand.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:669"
        ),
        target(
            "Chrome service worker cache",
            "\(chromeSupport)/*/Service Worker/CacheStorage",
            kind: .glob,
            explanation: "Per-origin service-worker CacheStorage. Never touches ScriptCache (MV3 extension bytecode) and honors the protected-domain list.",
            processGuard: chromeGuard,
            source: "mole lib/clean/user.sh:1734"
        ),
        target(
            "GoogleUpdater CRX cache",
            "Library/Application Support/Google/GoogleUpdater/crx_cache",
            kind: .directorySweep,
            explanation: "GoogleUpdater component payload cache. Re-fetched by the updater.",
            source: "mole lib/clean/user.sh:1737"
        ),
        target(
            "GoogleUpdater old files",
            "Library/Application Support/Google/GoogleUpdater/*.old",
            kind: .glob,
            explanation: "Superseded updater artifacts renamed .old during updates.",
            source: "mole lib/clean/user.sh:1738"
        ),
        target(
            "Chromium cache",
            "Library/Caches/Chromium",
            kind: .directorySweep,
            explanation: "Chromium open-source build's cache root. Same layout as Chrome's.",
            source: "mole lib/clean/user.sh:1739"
        ),
        appBundle(
            "Chrome old versions (system app)",
            "/Applications/Google Chrome.app",
            framework: "Google Chrome Framework.framework",
            explanation: "Old Chrome framework versions under Contents/Frameworks/.../Versions. Keeps the Current symlink target and any newer staged auto-update; may need elevated permissions to remove.",
            source: "mole lib/clean/user.sh:688",
            processGuard: chromeGuard
        ),
        appBundle(
            "Chrome old versions (user app)",
            "Applications/Google Chrome.app",
            framework: "Google Chrome Framework.framework",
            explanation: "Same pruning for a per-user Chrome install. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:693",
            processGuard: chromeGuard
        ),

        // -- Edge ------------------------------------------------------------------
        target(
            "Edge cache",
            "Library/Caches/com.microsoft.edgemac",
            kind: .directorySweep,
            explanation: "Microsoft Edge HTTP cache. Rebuilt as you browse.",
            source: "mole lib/clean/user.sh:1741"
        ),
        appBundle(
            "Edge old versions (system app)",
            "/Applications/Microsoft Edge.app",
            framework: "Microsoft Edge Framework.framework",
            explanation: "Old Edge framework versions. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:704",
            processGuard: edgeGuard
        ),
        appBundle(
            "Edge old versions (user app)",
            "Applications/Microsoft Edge.app",
            framework: "Microsoft Edge Framework.framework",
            explanation: "Same pruning for a per-user Edge install. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:709",
            processGuard: edgeGuard
        ),
        target(
            "Edge updater old versions",
            "Library/Application Support/Microsoft/EdgeUpdater/apps/msedge-stable",
            kind: .directorySweep,
            explanation: "EdgeUpdater staged payloads. There is no Current symlink here: keeps anything not strictly older than the installed Edge version.",
            processGuard: edgeGuard,
            pruneRule: .keepInstalledOrNewerVersion,
            source: "mole lib/clean/user.sh:720"
        ),

        // -- Brave -----------------------------------------------------------------
        target(
            "Brave cache",
            "Library/Caches/BraveSoftware/Brave-Browser",
            kind: .directorySweep,
            explanation: "Brave's HTTP cache root. Rebuilt as you browse; profile data is untouched.",
            source: "mole lib/clean/user.sh:1816"
        ),
        target(
            "Brave app cache",
            "\(braveSupport)/*/Application Cache/*",
            kind: .glob,
            explanation: "Per-profile legacy app cache. Regenerated by the pages that use it.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1821"
        ),
        target(
            "Brave code cache",
            "\(braveSupport)/*/Code Cache/*",
            kind: .glob,
            explanation: "Compiled JavaScript bytecode per profile. Recompiled on next page load.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1822"
        ),
        target(
            "Brave GPU cache",
            "\(braveSupport)/*/GPUCache/*",
            kind: .glob,
            explanation: "GPU shader/command scratch per profile. Rebuilt by the GPU process.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1823"
        ),
        target(
            "Brave Dawn cache",
            "\(braveSupport)/*/DawnCache/*",
            kind: .glob,
            explanation: "WebGPU/Dawn pipeline cache per profile. Regenerated on next WebGPU use.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1824"
        ),
        target(
            "Brave GR shader cache",
            "\(braveSupport)/*/GrShaderCache/*",
            kind: .glob,
            explanation: "Skia shader cache per profile. Recompiled as pages render.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1825"
        ),
        target(
            "Brave Graphite Dawn cache",
            "\(braveSupport)/*/GraphiteDawnCache/*",
            kind: .glob,
            explanation: "Graphite-backed WebGPU cache per profile. Regenerated on demand.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1826"
        ),
        target(
            "Brave component CRX cache",
            "\(braveSupport)/component_crx_cache",
            kind: .directorySweep,
            explanation: "Component-updater extension payloads. Re-downloaded by the updater.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1827"
        ),
        target(
            "Brave shader cache",
            "\(braveSupport)/ShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level shader cache. Recompiled as pages render.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1828"
        ),
        target(
            "Brave GR shader cache",
            "\(braveSupport)/GrShaderCache",
            kind: .directorySweep,
            explanation: "Browser-level Skia shader cache. Recompiled as pages render.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1829"
        ),
        target(
            "Brave Dawn cache",
            "\(braveSupport)/GraphiteDawnCache",
            kind: .directorySweep,
            explanation: "Browser-level Graphite/WebGPU cache. Regenerated on demand.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1830"
        ),
        target(
            "Brave crash reports",
            "\(braveSupport)/Crashpad/completed",
            kind: .directorySweep,
            explanation: "Minidumps already offered for upload. Purely diagnostic.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1831"
        ),
        target(
            "Brave service worker cache",
            "\(braveSupport)/*/Service Worker/CacheStorage",
            kind: .glob,
            explanation: "Per-origin service-worker CacheStorage. ScriptCache (MV3 bytecode) and protected domains are never touched.",
            processGuard: braveGuard,
            source: "mole lib/clean/user.sh:1833"
        ),
        appBundle(
            "Brave old versions (system app)",
            "/Applications/Brave Browser.app",
            framework: "Brave Browser Framework.framework",
            explanation: "Old Brave framework versions. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:853",
            processGuard: braveGuard
        ),
        appBundle(
            "Brave old versions (user app)",
            "Applications/Brave Browser.app",
            framework: "Brave Browser Framework.framework",
            explanation: "Same pruning for a per-user Brave install. Keeps the Current symlink target and any newer staged auto-update.",
            source: "mole lib/clean/user.sh:858",
            processGuard: braveGuard
        ),

        // -- Firefox ----------------------------------------------------------------
        target(
            "Firefox cache",
            "Library/Caches/Firefox",
            kind: .directorySweep,
            explanation: "Firefox HTTP cache root. Rebuilt as you browse.",
            processGuard: firefoxGuard,
            source: "mole lib/clean/user.sh:674"
        ),
        target(
            "Firefox profile cache",
            "Library/Application Support/Firefox/Profiles/*/cache2/*",
            kind: .glob,
            explanation: "Per-profile cache2 contents. Regenerated on next use; bookmarks, history and logins are untouched.",
            processGuard: firefoxGuard,
            source: "mole lib/clean/user.sh:676"
        ),
    ]
}
