import Foundation

// MARK: - System Paths table
// Ported from tw93/Mole lib/clean/system.sh (GPL-3.0), `clean_deep_system`,
// plus the broken-LaunchAgent audit from lib/optimize/tasks.sh (report-only
// by upstream design). Data only — no disk access.
// Every root-owned row here sets needsAdmin and is report-only: Mole needs a
// sudo session for these, and Tebo's own pipeline never elevates.

public enum SystemPaths {

    // Root-owned row: absolute path, needsAdmin, report-only.
    private static func adminTarget(
        _ label: String,
        _ path: String,
        kind: MoleTargetKind,
        risk: MoleRisk = .safe,
        explanation: String,
        source: String
    ) -> CleanTarget {
        CleanTarget(
            label: label,
            group: .systemPaths,
            path: .absolute(path),
            kind: kind,
            risk: risk,
            needsAdmin: true,
            explanation: explanation,
            reportOnly: true,
            source: source
        )
    }

    private static let logAge = 7 * 24 * 60 // MOLE_LOG_AGE_DAYS = 7
    private static let tempAge = 7 * 24 * 60 // MOLE_TEMP_FILE_AGE_DAYS = 7

    public static let all: [CleanTarget] = [
        // -- clean_deep_system (system.sh:224) ---------------------------------------
        adminTarget(
            "System caches",
            "/Library/Caches",
            kind: .findRule(maxDepth: 5, minAgeMinutes: tempAge, filesOnly: true),
            explanation: "Root-owned system cache files (*.cache, *.tmp; *.log when log/temp retention match) older than 7 days. Caches are rebuilt by their owning services. Requires admin; Tebo only reports this row.",
            source: "mole lib/clean/system.sh:238"
        ),
        adminTarget(
            "System crash reports",
            "/Library/Logs/DiagnosticReports",
            kind: .findRule(maxDepth: 1, minAgeMinutes: 7 * 24 * 60, filesOnly: true),
            explanation: "System-level crash reports older than 7 days (MOLE_CRASH_REPORT_AGE_DAYS). Already-uploaded diagnostic data. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:281"
        ),
        adminTarget(
            "System logs",
            "/private/var/log",
            kind: .findRule(maxDepth: 3, minAgeMinutes: logAge, filesOnly: true),
            explanation: "Rotating system log files (*.log, *.gz, *.asl) older than 7 days. Old diagnostic text only, never live state. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:303"
        ),
        adminTarget(
            "Adobe system logs",
            "/Library/Logs/Adobe",
            kind: .findRule(maxDepth: 5, minAgeMinutes: logAge, filesOnly: true),
            explanation: "Third-party Adobe logs older than 7 days. Purely informational. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:327"
        ),
        adminTarget(
            "CreativeCloud system logs",
            "/Library/Logs/CreativeCloud",
            kind: .findRule(maxDepth: 5, minAgeMinutes: logAge, filesOnly: true),
            explanation: "Creative Cloud logs older than 7 days. Purely informational. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:328"
        ),
        adminTarget(
            "Adobe GC log",
            "/Library/Logs/adobegc.log",
            kind: .file,
            explanation: "Adobe garbage-collector log file, removed once older than 7 days. Purely diagnostic. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:358"
        ),
        adminTarget(
            "Rebuildable system caches",
            "/Library/Caches/com.apple.iconservices.store",
            kind: .directory,
            explanation: "System icon-services store. Rebuilt by iconservicesd in the background. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:580"
        ),
        adminTarget(
            "Browser code signature caches",
            "/private/var/folders",
            kind: .findRule(maxDepth: 5, minAgeMinutes: 0, filesOnly: false),
            explanation: "Browser *.code_sign_clone dirs under each user's per-user temp tree (*/X/*). Endpoint-security agents are skipped. Regenerated by the browser. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:531"
        ),
        adminTarget(
            "Rebuildable GPU caches",
            "/private/var/folders",
            kind: .findRule(maxDepth: 8, minAgeMinutes: 24 * 60, filesOnly: false),
            explanation: "Stale com.apple.gpuarchiver/com.apple.metal/com.apple.metalfe dirs under per-user cache trees (*/C/*), older than 1 day (MOLE_GPU_CACHE_AGE_DAYS). Rebuilt by Metal on demand. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:648"
        ),
        adminTarget(
            "Stale wallpaper downloads",
            "/private/var/folders",
            kind: .findRule(maxDepth: 5, minAgeMinutes: tempAge, filesOnly: true),
            explanation: "Aborted CFNetworkDownload_*.tmp files under com.apple.idleassetsd per-user temp dirs (*/T/*), older than 7 days. macOS re-fetches the wallpaper assets on demand. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:733"
        ),
        adminTarget(
            "System diagnostic logs",
            "/private/var/db/diagnostics",
            kind: .findRule(maxDepth: 5, minAgeMinutes: logAge, filesOnly: true),
            explanation: "Unified-log diagnostic store files older than 7 days. Purely informational. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:780"
        ),
        adminTarget(
            "Diagnostic pipeline logs",
            "/private/var/db/DiagnosticPipeline",
            kind: .findRule(maxDepth: 5, minAgeMinutes: logAge, filesOnly: true),
            explanation: "Diagnostic pipeline scratch older than 7 days. Rebuilt on demand. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:797"
        ),
        adminTarget(
            "Power logs",
            "/private/var/db/powerlog",
            kind: .findRule(maxDepth: 5, minAgeMinutes: logAge, filesOnly: true),
            explanation: "Battery/power telemetry older than 7 days. Purely diagnostic. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:823"
        ),
        adminTarget(
            "Memory exception reports",
            "/private/var/db/reportmemoryexception/MemoryLimitViolations",
            kind: .findRule(maxDepth: 5, minAgeMinutes: 30 * 24 * 60, filesOnly: true),
            explanation: "Memory-limit violation reports older than 30 days. Purely diagnostic. Requires admin; report-only.",
            source: "mole lib/clean/system.sh:882"
        ),
        adminTarget(
            "macOS installer apps",
            "/Applications/Install macOS*.app",
            kind: .glob,
            risk: .review,
            explanation: "Install macOS *.app bundles older than 14 days, kept when not running, current-version matching, recent or update-state-unknown (Mole's eligibility checks). Review before removing; requires admin; report-only.",
            source: "mole lib/clean/system.sh:415"
        ),

        // -- Broken LaunchAgent audit (report-only upstream, never deletes) -----------
        CleanTarget(
            label: "Broken user LaunchAgents",
            group: .systemPaths,
            path: .homeRelative("Library/LaunchAgents"),
            kind: .directorySweep,
            risk: .review,
            explanation: "Mole's optimize audit only REPORTS LaunchAgents whose absolute program path is missing: it never deletes the plist or unloads the label, because a missing executable does not prove the service is unwanted. Tebo mirrors that: report-only.",
            reportOnly: true,
            source: "mole lib/optimize/tasks.sh:1177"
        ),
    ]
}

