import Foundation

// MARK: - User Essentials table
// Ported from tw93/Mole lib/clean/user.sh (GPL-3.0), `clean_user_essentials`,
// `clean_trash`, `_clean_recent_items`, `_clean_incomplete_downloads`,
// `_clean_mail_downloads`. Data only — no disk access.

/// Sweeps every child of the user's Library/Caches, plus logs, Trash,
/// recent-items lists, incomplete downloads and stale Mail attachments.
public enum UserEssentials {

    // Builds a row for this table: home-relative, safe by default.
    private static func target(
        _ label: String,
        _ path: String,
        kind: MoleTargetKind,
        explanation: String,
        risk: MoleRisk = .safe,
        processGuard: MoleProcessGuard? = nil,
        reportOnly: Bool = false,
        source: String
    ) -> CleanTarget {
        CleanTarget(
            label: label,
            group: .userEssentials,
            path: .homeRelative(path),
            kind: kind,
            risk: risk,
            explanation: explanation,
            processGuard: processGuard,
            reportOnly: reportOnly,
            source: source
        )
    }

    public static let all: [CleanTarget] = [
        // -- User app cache / logs ------------------------------------------------
        target(
            "User app cache",
            "Library/Caches",
            kind: .directorySweep,
            explanation: "Sweeps every per-app cache dir under ~/Library/Caches. All of it is regenerated by apps on demand; Mole's default whitelist keeps JetBrains, ollama models, Surge, Finder metadata and the Deno root out of the sweep.",
            source: "mole lib/clean/user.sh:178"
        ),
        target(
            "User app logs",
            "Library/Logs",
            kind: .directorySweep,
            explanation: "Rotating per-app log files. Pruning them loses only old diagnostic text, never app state.",
            source: "mole lib/clean/user.sh:215"
        ),

        // -- Trash (report-only) --------------------------------------------------
        target(
            "Trash",
            ".Trash",
            kind: .directorySweep,
            explanation: "Mole empties ~/.Trash directly. Tebo only reports its size: emptying the Trash is a user decision because it is the last copy of deleted files.",
            risk: .review,
            reportOnly: true,
            source: "mole lib/clean/user.sh:37"
        ),

        // -- Recent items (LaunchServices shared file lists) ----------------------
        target(
            "Recent applications list (sfl2)",
            "Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentApplications.sfl2",
            kind: .file,
            explanation: "LaunchServices recency metadata for the Apple menu / Dock recent-apps list. Rebuilt as you open apps.",
            source: "mole lib/clean/user.sh:233"
        ),
        target(
            "Recent documents list (sfl2)",
            "Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentDocuments.sfl2",
            kind: .file,
            explanation: "LaunchServices recency metadata for the Open Recent documents menu. Rebuilt as you open files.",
            source: "mole lib/clean/user.sh:234"
        ),
        target(
            "Recent servers list (sfl2)",
            "Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentServers.sfl2",
            kind: .file,
            explanation: "Recency metadata for recently connected servers. Rebuilt on next connect.",
            source: "mole lib/clean/user.sh:235"
        ),
        target(
            "Recent hosts list (sfl2)",
            "Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentHosts.sfl2",
            kind: .file,
            explanation: "Recency metadata for recent hosts. Rebuilt on next use.",
            source: "mole lib/clean/user.sh:236"
        ),
        target(
            "Recent applications list (sfl)",
            "Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentApplications.sfl",
            kind: .file,
            explanation: "Legacy sfl variant of the recent-applications list. Rebuilt by LaunchServices.",
            source: "mole lib/clean/user.sh:237"
        ),
        target(
            "Recent documents list (sfl)",
            "Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentDocuments.sfl",
            kind: .file,
            explanation: "Legacy sfl variant of the recent-documents list. Rebuilt by LaunchServices.",
            source: "mole lib/clean/user.sh:238"
        ),
        target(
            "Recent servers list (sfl)",
            "Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentServers.sfl",
            kind: .file,
            explanation: "Legacy sfl variant of the recent-servers list. Rebuilt on next connect.",
            source: "mole lib/clean/user.sh:239"
        ),
        target(
            "Recent hosts list (sfl)",
            "Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.RecentHosts.sfl",
            kind: .file,
            explanation: "Legacy sfl variant of the recent-hosts list. Rebuilt on next use.",
            source: "mole lib/clean/user.sh:240"
        ),
        target(
            "Recent items preferences",
            "Library/Preferences/com.apple.recentitems.plist",
            kind: .file,
            explanation: "Preference plist storing recent-items UI state. macOS recreates it with defaults.",
            source: "mole lib/clean/user.sh:247"
        ),

        // -- Incomplete downloads -------------------------------------------------
        target(
            "Safari incomplete downloads",
            "Downloads/*.download",
            kind: .glob,
            explanation: "Safari download scratch bundles. Skipped while the file still has an open handle, so active downloads are never cut off.",
            source: "mole lib/clean/user.sh:278"
        ),
        target(
            "Chrome incomplete downloads",
            "Downloads/*.crdownload",
            kind: .glob,
            explanation: "Chrome in-progress download stubs. Skipped while the file still has an open handle.",
            source: "mole lib/clean/user.sh:279"
        ),
        target(
            "Partial incomplete downloads",
            "Downloads/*.part",
            kind: .glob,
            explanation: "Generic partial-download stubs. Skipped while the file still has an open handle.",
            source: "mole lib/clean/user.sh:280"
        ),

        // -- Old Mail attachments -------------------------------------------------
        target(
            "Mail downloads (legacy)",
            "Library/Mail Downloads",
            kind: .findRule(maxDepth: nil, minAgeMinutes: 30 * 24 * 60, filesOnly: true),
            explanation: "Attachments saved from Mail, deleted only when older than 30 days. The original mail keeps the attachment, so these are duplicate copies.",
            processGuard: .exact("Mail"),
            source: "mole lib/clean/user.sh:333"
        ),
        target(
            "Mail downloads (sandboxed Mail)",
            "Library/Containers/com.apple.mail/Data/Library/Mail Downloads",
            kind: .findRule(maxDepth: nil, minAgeMinutes: 30 * 24 * 60, filesOnly: true),
            explanation: "Same 30-day rule for the sandboxed Mail app's download folder; the original mail keeps the attachment.",
            processGuard: .exact("Mail"),
            source: "mole lib/clean/user.sh:335"
        ),
    ]
}
